# Generated by Django 5.2 on 2025-05-06 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_url_click_count_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(),
        ),
    ]
