# Generated by Django 5.2 on 2025-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_url_last_clicked_alter_url_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-created_at'], 'verbose_name': 'URL Entry', 'verbose_name_plural': 'URL Entries'},
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
